Spring security
wolox-training/cr-java pull request #13
Opened 2019-08-16 17:29 UTC by cramallo

## Summary

- Add Spring security configuration.
- Add a custom authentication provider.
- Add password to user model.
- Add BCrypt library to encrypt the passwords.

## Known Issues

- Some changes in test to fix errors.

## Trello Card

https://trello.com/c/dra1uUMo/23-integrar-spring-security

2019-08-20 14:03 UTC, rodrigofranc approved these changes
This works great. Maybe adding roles and privilege is more robust solution

2019-08-20 19:18 UTC, IgnOliveto requested changes

2019-08-20 19:18 UTC, IgnOliveto commented on src/main/java/com/wolox/training/security/BasicConfiguration.java
> +    protected void configure(HttpSecurity http) throws Exception {
May you can do this without the need to include every protected url, you can use web.ignoring().antMatchers.
Read [this](http://blog.florian-hopf.de/2017/08/spring-security.html) for more info

2019-08-21 14:23 UTC, IgnOliveto approved these changes

2019-08-21 14:52 UTC, merged