adding book crud endpoints in controller, methods in service and erro…
wolox-training/cr-java pull request #5
Opened 2019-08-07 13:35 UTC by cramallo

## Summary

- Create Book Model.

- Add CRUD book endpoints.
- Add methods to book service.
- Add handling errors.

## Known Issues

## Trello Card

https://trello.com/c/3v0bpU0n/18-crear-las-operaciones-crud-de-book

2019-08-07 15:57 UTC, IgnOliveto requested changes

2019-08-07 15:57 UTC, IgnOliveto commented on src/main/java/com/wolox/training/dtos/BookDTO.java
> +    private int id;
Why if the id of the book class is a long the dto is integer? we should maintain uniformity of types between the dtos and the classes they represent.

2019-08-07 15:57 UTC, IgnOliveto commented on src/main/java/com/wolox/training/services/BookService.java
> +            throw new BadRequestException("Invalid book fields");
We should use a class that contains the error messages as constants, we should not have them literal in the place where the exception is raised

2019-08-07 15:57 UTC, IgnOliveto commented on src/main/java/com/wolox/training/services/BookService.java
> +            throw new ServerErrorException("Internal server error");
We should use a class that contains the error messages as constants, we should not have them literal in the place where the exception is raised

2019-08-07 15:57 UTC, IgnOliveto commented on src/main/java/com/wolox/training/services/BookService.java
> +            throw new ServerErrorException("Internal server error");
We should use a class that contains the error messages as constants, we should not have them literal in the place where the exception is raised

2019-08-07 15:57 UTC, IgnOliveto commented on src/main/java/com/wolox/training/services/BookService.java
> +            throw new BadRequestException("Invalid book fields");
We should use a class that contains the error messages as constants, we should not have them literal in the place where the exception is raised

2019-08-07 15:57 UTC, IgnOliveto commented on src/main/java/com/wolox/training/services/BookService.java
> +        return bookRepository.findById(id).orElseThrow(()->new NotFoundException("book not found"));
We should use a class that contains the error messages as constants, we should not have them literal in the place where the exception is raised

2019-08-07 15:57 UTC, IgnOliveto commented on src/main/java/com/wolox/training/services/BookService.java
> +public class BookService {
I liked that you use services to encapsulate logic that should not be in the controller, but in this method validations are made of the attributes of objects of the book class that should be done with annotation at  model level.

2019-08-07 17:56 UTC, IgnOliveto requested changes

2019-08-07 17:56 UTC, IgnOliveto commented on src/main/java/com/wolox/training/models/Book.java
> +    public Book(String genre, @NotNull String author,@NotNull String image, @NotNull String title,@NotNull String subtitle,
This validations only work in this constructor, look the validation in this [example](https://www.baeldung.com/javax-validation)

2019-08-08 17:53 UTC, IgnOliveto approved these changes
Good Work!

2019-08-09 16:44 UTC, rodrigofranc approved these changes

2019-08-09 16:44 UTC, rodrigofranc commented on src/main/java/com/wolox/training/controllers/BookController.java
> +@RestController
When define the endpoint and you have a prefix for all routes, you can include the annotation @RequestMapping in class definition, like this:

```
@RestController
@RequestMapping("/book")
public class BookController {
```
then for example in the delete method:

```
@DeleteMapping("/{id}")
public void deleteBook(@PathVariable("id") int bookId){
```

2019-08-09 16:44 UTC, rodrigofranc commented on src/main/java/com/wolox/training/controllers/BookController.java
> +    public BookDTO createBook(@RequestBody BookDTO bookDto){
For the rest standard it is a good practice to include the status code according to the operation. You can do this with annotations in spring. For example: @ResponseStatus(HttpStatus.CREATED)

2019-08-09 17:03 UTC, merged