User Model
wolox-training/cr-java pull request #6
Opened 2019-08-07 14:57 UTC by cramallo

## Summary

- Add User Model.
- Add handling errors in this model.

## Known Issues

## Trello Card

https://trello.com/c/nGIFooLs/19-crear-modelo-de-user

2019-08-07 16:14 UTC, IgnOliveto requested changes

2019-08-07 16:14 UTC, IgnOliveto commented on src/main/java/com/wolox/training/models/User.java
> +    private int id;
Missing a get method for the user id.

2019-08-07 16:14 UTC, IgnOliveto commented on src/main/java/com/wolox/training/models/User.java
> +            throw new BookAlreadyOwnException("User already has this book");
We need a class that contains constants with error messages to avoid appearing literals where the exception is raised

2019-08-09 16:45 UTC, rodrigofranc approved these changes

2019-08-09 16:48 UTC, IgnOliveto approved these changes
Good Job!

2019-08-09 17:05 UTC, merged